# LG Therma V 7.0kW HM071MR.U44
#
# On the indoor remote controller:
# - Set modbus address to 0x01
#
# On the circuit board:
# - DIP SW1: Set 1 to the left (modbus slave)
# - DIP SW1: Set 2 to the left (modbus common 3rd party)
# - DIP SW2: Set 1 to the right
# - No termination resistor on the A/B terminals

esphome:
  name: lg-therma

esp32:
  board: esp32thing
  framework:
    type: arduino


logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  password: !secret ota_password

mqtt:
  broker: mqtt.local


uart:
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600
  id: uart_modbus
  parity: none
  data_bits: 8
  stop_bits: 1

modbus:
  id: modbus_lg
  uart_id: uart_modbus

modbus_controller:
  - id: lg
    address: 0x01  # The Modbus addr as configured in the LG Remote
    modbus_id: modbus_lg
    setup_priority: -10
    update_interval: 30s


switch:
  - platform: modbus_controller
    id: active
    name: "Active"
    icon: mdi:power
    modbus_controller_id: lg
    register_type: coil
    address: 0

  - platform: modbus_controller
    name: "Silent Mode"
    icon: mdi:volume-off
    modbus_controller_id: lg
    register_type: coil
    address: 2

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Low Flow"
    icon: mdi:pump-off
    register_type: discrete_input
    address: 0

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Pump Running"
    icon: mdi:pump
    register_type: discrete_input
    address: 1

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Compressor Running"
    icon: mdi:car-turbocharger
    register_type: discrete_input
    address: 3

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Defrosting"
    icon: mdi:snowflake-melt
    register_type: discrete_input
    address: 4

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Silent Mode On"
    icon: mdi:volume-off
    register_type: discrete_input
    address: 7

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Error"
    icon: mdi:alert-outline
    register_type: discrete_input
    address: 13

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    state_topic: esphome/lg-therma/version

  - platform: template
    id: lg_therma_mode
    name: "Mode"
    icon: mdi:sun-snowflake-variant

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    update_interval: 10s
    state_topic: esphome/lg-therma/wifi_signal
    retain: false

  - platform: modbus_controller
    modbus_controller_id: lg
    id: lg_therma_mode_raw
    state_topic: null
    register_type: read
    register_count: 2
    address: 1
    value_type: U_WORD
    on_value:
      - text_sensor.template.publish:
          id: lg_therma_mode
          state: !lambda |-
            return x == 0 ? "Off"
                 : x == 1 ? "Cool"
                 : x == 2 ? "Heat"
                 : "???";

  - platform: modbus_controller
    modbus_controller_id: lg
    id: inlet_temp
    name: "Water Inlet"
    icon: mdi:thermometer-chevron-down
    register_type: read
    address: 2
    register_count: 2
    value_type: S_WORD
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: lg
    id: outlet_temp
    name: "Water Outlet"
    icon: mdi:thermometer-chevron-up
    register_type: read
    address: 3
    register_count: 2
    value_type: S_WORD
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "INPUT 4"
    register_type: read
    address: 4
    register_count: 2
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "INPUT 5"
    register_type: read
    address: 5
    register_count: 2
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "INPUT 6"
    register_type: read
    address: 6
    register_count: 2
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Room Air Temperature"
    register_type: read
    address: 7
    register_count: 2
    value_type: S_WORD
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: lg
    id: flow_rate
    name: "Flow Rate"
    icon: mdi:waves-arrow-right
    register_type: read
    address: 8
    register_count: 2
    value_type: U_WORD
    unit_of_measurement: "L/m"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "INPUT 9"
    register_type: read
    address: 9
    register_count: 2
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "INPUT 10"
    register_type: read
    address: 10
    register_count: 2
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "INPUT 11"
    register_type: read
    address: 11
    register_count: 2
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Outside Temperature"
    register_type: read
    address: 12
    register_count: 2
    value_type: S_WORD
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # addresses 13,14,15 are not used

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "INPUT 16"
    register_type: read
    address: 16
    register_count: 2
    value_type: S_WORD
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "INPUT 17"
    register_type: read
    address: 17
    register_count: 2
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Refridgerant Cool"
    icon: mdi:thermometer-minus
    register_type: read
    address: 18
    register_count: 2
    value_type: S_WORD
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Refridgerant Hot"
    icon: mdi:thermometer-plus
    register_type: read
    address: 19
    register_count: 2
    value_type: S_WORD
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "INPUT 20"
    register_type: read
    address: 20
    register_count: 2
    value_type: S_WORD
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

    # 21 is a mystery temperature sensor.

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Condenser Pressure"
    icon: mdi:gauge
    register_type: read
    address: 22
    register_count: 2
    value_type: U_WORD
    unit_of_measurement: mbar
    state_class: "measurement"

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Evaporator Pressure"
    icon: mdi:gauge-low
    register_type: read
    address: 23
    register_count: 2
    value_type: U_WORD
    unit_of_measurement: mbar
    state_class: "measurement"

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Compressor Speed"
    icon: mdi:car-turbocharger
    register_type: read
    address: 24
    value_type: U_WORD
    unit_of_measurement: "Hz"
    state_class: "measurement"
    accuracy_decimals: 0

  - platform: template
    id: water_delta_t
    name: "Water ΔT"
    icon: mdi:delta
    lambda: |-
      return id(outlet_temp).state - id(inlet_temp).state;
    unit_of_measurement: "°C"
    state_class: "measurement"

  - platform: template
    name: "Power Output"
    icon: mdi:heat-wave
    lambda: |-
      // Set the value to 0 when off. This accounts for drifting water temperatures which can result
      // in weird readings. The flow sensor also seems to default to a non-zero value when off which
      // does not help either.
      if (!id(active).state) {
        return 0.0;
      }
      // Water has a specific heat of 4184 joule per kilogram/degree.
      const double specific_heat = 4184.0;
      double flow_lps = id(flow_rate).state / 60.0;
      // Δt * c * L/sec = Joule/sec = Watt
      return id(water_delta_t).state * specific_heat * flow_lps;
    unit_of_measurement: "Watt"
    state_class: "measurement"
    accuracy_decimals: 0

select:
  - platform: modbus_controller
    modbus_controller_id: lg
    name: Operation Mode
    icon: mdi:sun-snowflake-variant
    address: 0
    value_type: U_WORD
    optionsmap:
      "Cool": 0
      "Heat": 4
      "Auto": 5

  - platform: modbus_controller
    modbus_controller_id: lg
    name: Reference
    icon: mdi:thermometer
    address: 1
    value_type: U_WORD
    optionsmap:
      "Water Outlet": 0
      "Water Inlet": 1
      "Room Air": 2

number:
  - platform: modbus_controller
    name: "Target Temperature"
    icon: mdi:thermometer
    address: 2
    min_value: 16
    max_value: 30
    step: 1
    multiply: 10
    device_class: "temperature"
    unit_of_measurement: "°C"

  - platform: modbus_controller
    name: "Set Room Air Temperature"
    icon: mdi:home-thermometer
    address: 3
    min_value: 10
    max_value: 40
    step: 1
    multiply: 10
    device_class: "temperature"
    unit_of_measurement: "°C"
